"""Hindi (Devanagari), Marathi (Devanagari) and romanised-Hindi ("Hinglish") police / legal glossary.

Line format:   variant1, variant2 = English | CATEGORY
Categories:    N (default) noun/phrase, V verb, ADJ, ADV, AUX (is/was), NEG, CONJ, PRON, NUM, P:<kind> postposition
               (kind = agent, dat, abl, loc, on, gen, til, for, with, by, near, of, from, without ...), LBL form label
Inflections (plural / oblique / feminine) are handled by rules in translation.py; only base forms are listed here.
Marathi lines are used only when the sentence is detected as Marathi (they can override the shared Devanagari table).
"""

HI = """
# --- additions: common narrative words and rank titles
सब इंस्पेक्टर, सब-इंस्पेक्टर, सबइंस्पेक्टर, सब इन्स्पेक्टर, सहायक उप निरीक्षक = Sub-Inspector
असिस्टेंट सब इंस्पेक्टर, सहायक उपनिरीक्षक = Assistant Sub-Inspector
हेड कांस्टेबल, हेड कांस्टेबिल = Head Constable
घटना = incident
बंद = closed
वे, वो = they | PRON
जिसमें = in which | CONJ
रोककर, रोक कर, रोका = stopped | V
दिखाया, दिखाकर, दिखा कर = showed | V

# --- form labels / document structure
प्रथम सूचना रिपोर्ट, प्रथम सूचना प्रतिवेदन = First Information Report | LBL
प्रथम माहिती अहवाल = First Information Report | LBL
प्राथमिकी = FIR
एफआईआर, एफआयआर, एफ.आई.आर., एफ आई आर = FIR
एफआईआर क्रमांक, एफआयआर क्रमांक, एफआईआर संख्या, एफआईआर नंबर = FIR No. | LBL
जिला, जनपद = District | LBL
जिल्हा = District | LBL
थाना, पुलिस थाना, थाने, पुलिस स्टेशन, थाना क्षेत्र = Police Station
वर्ष, सन = Year | LBL
दिनांक, तारीख, तिथि, तारीख़ = Date | LBL
समय, वक्त = Time | LBL
घटना का स्थान, घटनास्थल, घटना स्थल, वारदात का स्थान, घटना की जगह = Place of occurrence | LBL
घटना का विवरण, घटना का संक्षिप्त विवरण, विवरण, घटना विवरण = Incident details | LBL
शिकायतकर्ता, वादी, प्रार्थी, सूचनाकर्ता, परिवादी = Complainant
सूचक = Informant
पिता का नाम, पिता = Father's name
माता का नाम, माता = Mother's name
पति का नाम = Husband's name
पता, पते, ठिकाना = Address
नं, नं., नम्बर, नंबर = No.
निवासी, साकिन = resident of
मोबाइल, मोबाईल, मोबाइल नंबर, मोबाइल नं, दूरभाष = Mobile
फोन, फ़ोन, टेलीफोन = phone
आरोपी, अभियुक्त, मुल्जिम, मुलजिम = Accused
संदिग्ध, संदेही, शक = Suspect
अज्ञात = Unknown
अज्ञात व्यक्ति = unknown person
अज्ञात लोग, अज्ञात व्यक्तियों = unknown persons
अज्ञात बदमाश = unknown miscreants
जांच अधिकारी, विवेचक, विवेचना अधिकारी, जाँच अधिकारी = Investigating Officer | LBL
जनरल डायरी, रोजनामचा, सामान्य डायरी = General Diary
चोरी की संपत्ति, चोरी गई संपत्ति, चोरी गया माल = stolen property | LBL
संपत्ति, सम्पत्ति, माल, मालमत्ता = property
सम्बंधित धाराएं, धाराएं, धाराएँ, धारा = Sections | LBL
अधिनियम = Act
संहिता = Code
भारतीय दंड संहिता, भारतीय दण्ड संहिता = Indian Penal Code
भादंवि, भा.दं.वि., भा.द.वि. = IPC
भारतीय न्याय संहिता = Bharatiya Nyaya Sanhita
सूचना प्रौद्योगिकी अधिनियम, आईटी एक्ट = Information Technology Act
दहेज प्रतिषेध अधिनियम = Dowry Prohibition Act
मादक पदार्थ = narcotic substances
एनडीपीएस एक्ट = NDPS Act
आर्म्स एक्ट, शस्त्र अधिनियम = Arms Act
पॉक्सो = POCSO
भ्रष्टाचार निवारण अधिनियम = Prevention of Corruption Act
धन शोधन = money laundering
मुकदमा, मामला, प्रकरण, केस = case
मुकदमा दर्ज, मामला दर्ज, केस दर्ज, प्रकरण दर्ज, रिपोर्ट दर्ज = case registered
रिपोर्ट = report
शिकायत, तहरीर = complaint
प्रार्थना पत्र, प्रार्थनापत्र, आवेदन = application
गवाह, साक्षी, चश्मदीद = witness
पीड़ित, पीडित = victim
घायल, जख्मी, ज़ख्मी = injured
मृतक = deceased
वादी मुकदमा = complainant
प्रतिवादी = respondent
अपराध = crime
अपराधी = criminal
जुर्म = offence
गिरफ्तार, गिरफ़्तार = arrested
गिरफ्तारी = arrest
हिरासत = custody
जमानत, ज़मानत = bail
पूछताछ = questioning
बयान = statement
तलाशी = search
जब्त, ज़ब्त = seized
बरामद = recovered
बरामदगी = recovery
कब्जा, कब्ज़ा = possession
वारंट = warrant
न्यायालय, अदालत, कोर्ट = court
मजिस्ट्रेट = magistrate
वकील = lawyer
सबूत, साक्ष्य = evidence
सीसीटीवी, सीसीटीवी फुटेज = CCTV footage
फुटेज = footage
फोरेंसिक = forensic
पंचनामा = panchnama
मेडिकल, चिकित्सा जांच = medical examination
पोस्टमार्टम = post-mortem
# --- ranks / police
पुलिस = police
पुलिस अधीक्षक, एसपी = Superintendent of Police
उपनिरीक्षक, उप निरीक्षक, एसआई, दरोगा, दारोगा = Sub-Inspector
निरीक्षक, इंस्पेक्टर, थानाध्यक्ष, थानेदार = Inspector
सहायक उपनिरीक्षक, एएसआई = Assistant Sub-Inspector
हेड कांस्टेबल, हेड कान्स्टेबल = Head Constable
कांस्टेबल, कान्स्टेबल, सिपाही, आरक्षी = Constable
उपाधीक्षक, डीएसपी, क्षेत्राधिकारी = Deputy Superintendent of Police
अधिकारी = officer
कोतवाली = Kotwali (police station)
चौकी = outpost
गश्त = patrol
पीसीआर = PCR
# --- offences
चोरी = theft
चोर = thief
चोरों = thieves
डकैती = dacoity
लूट = robbery
लूटपाट = robbery
छीना झपटी, झपटमारी = snatching
हत्या = murder
हत्या का प्रयास = attempt to murder
जानलेवा हमला = murderous assault
मारपीट = assault
हमला = attack
बलात्कार = rape
छेड़छाड़, छेड़खानी = molestation
अपहरण = kidnapping
धोखाधड़ी, धोखाधडी = fraud
ठगी, ठग = cheating
जालसाजी, कूटरचना = forgery
रंगदारी = extortion
वसूली = extortion
धमकी = threat
ब्लैकमेल, ब्लैकमेलिंग = blackmail
दहेज = dowry
दहेज उत्पीड़न = dowry harassment
घरेलू हिंसा = domestic violence
क्रूरता = cruelty
तस्करी = smuggling
नशीला पदार्थ, नशीले पदार्थ, नशा = narcotics
गांजा = ganja
अफीम = opium
चरस = charas
हेरोइन = heroin
सेंधमारी, नकबजनी = house-breaking
आगजनी = arson
तोड़फोड़ = vandalism
जुआ = gambling
सट्टा = betting
रिश्वत, घूस = bribe
भ्रष्टाचार = corruption
गबन = embezzlement
अतिक्रमण = trespass
आपराधिक न्यास भंग = criminal breach of trust
आपराधिक षड्यंत्र, षड्यंत्र = criminal conspiracy
अवैध = illegal
अश्लील = obscene
गाली गलौज, गाली = abuse
शीलभंग = outraging modesty
आत्महत्या = suicide
आत्महत्या के लिए उकसाना = abetment of suicide
लापता, गुमशुदा, गुमशुदगी = missing
गुम = lost
गायब = missing
साइबर ठगी, साइबर धोखाधड़ी = cyber fraud
साइबर अपराध = cybercrime
ऑनलाइन ठगी = online fraud
हथियार, शस्त्र = weapon
चाकू = knife
छुरा = dagger
पिस्तौल, पिस्टल = pistol
तमंचा, कट्टा = country-made pistol
बंदूक = gun
गोली = bullet
कारतूस = cartridge
डंडा, लाठी = stick
लोहे की रॉड, रॉड = iron rod
ईंट = brick
पत्थर = stone
तेजाब = acid
# --- cyber / finance
ऑनलाइन = online
लिंक = link
ओटीपी = OTP
खाता, अकाउंट = account
बैंक खाता, बैंक खाते = bank account
खाता संख्या, खाता नंबर = account number
बैंक = bank
शाखा = branch
एटीएम = ATM
कार्ड = card
डेबिट कार्ड = debit card
क्रेडिट कार्ड = credit card
यूपीआई = UPI
लेनदेन, लेन-देन, ट्रांजैक्शन = transaction
ट्रांसफर = transfer
राशि, रकम, धनराशि = amount
रुपये, रुपए, रूपये, रु., रु = rupees
रुपया, रूपया = rupee
लाख = lakh
करोड़ = crore
हजार, हज़ार = thousand
नकद, नकदी, कैश = cash
पैसे, पैसा, रुपैया = money
निवेश = investment
ट्रेडिंग = trading
क्रिप्टो, क्रिप्टोकरेंसी = cryptocurrency
वॉलेट = wallet
लॉटरी = lottery
इनाम = prize
नौकरी = job
ऐप, एप, एप्लिकेशन = app
वेबसाइट = website
व्हाट्सएप, वॉट्सऐप, व्हाट्सऐप = WhatsApp
टेलीग्राम = Telegram
फेसबुक = Facebook
इंस्टाग्राम = Instagram
ईमेल, ई-मेल = email
पासवर्ड = password
संदेश, मैसेज = message
कॉल = call
वीडियो कॉल = video call
वीडियो = video
फोटो, तस्वीर = photo
सिम = SIM
सिम कार्ड = SIM card
आधार, आधार कार्ड = Aadhaar card
पैन, पैन कार्ड = PAN card
लाइसेंस, ड्राइविंग लाइसेंस = driving licence
चेक = cheque
एफडी = fixed deposit
कर्ज, ऋण, लोन = loan
ब्याज = interest
जमीन, ज़मीन = land
प्लॉट = plot
सौदा = deal
दस्तावेज, दस्तावेज़, कागजात = documents
फर्जी, फ़र्ज़ी, जाली = fake
नकली = counterfeit
# --- property / vehicles
मोबाइल फोन, मोबाइल फ़ोन, स्मार्टफोन = mobile phone
लैपटॉप, लैपटाप = laptop
कंप्यूटर = computer
टैबलेट = tablet
कैमरा = camera
बैग, बैग = bag
पर्स = purse
बटुआ = wallet
सोना, सोने = gold
चांदी, चाँदी = silver
गहने, जेवर, आभूषण, ज्वैलरी = jewellery
चेन, सोने की चेन = chain
अंगूठी = ring
मंगलसूत्र = mangalsutra
घड़ी = watch
चाबी, चाभी = key
ताला = lock
ताला तोड़कर = breaking the lock
मोटरसाइकिल, मोटर साइकिल = motorcycle
बाइक, बाईक = bike
स्कूटर, स्कूटी = scooter
कार = car
गाड़ी, वाहन = vehicle
ट्रक = truck
ऑटो, ऑटो रिक्शा = auto-rickshaw
साइकिल = bicycle
नंबर प्लेट = number plate
पंजीकरण संख्या, रजिस्ट्रेशन नंबर, गाड़ी नंबर = registration number
इंजन नंबर = engine number
चेसिस नंबर = chassis number
हेलमेट = helmet
काला, काले, काली = black
सफेद, सफ़ेद = white
लाल = red
नीला, नीले, नीली = blue
हरा, हरे, हरी = green
पीला, पीले, पीली = yellow
भूरा = brown
ग्रे, स्लेटी = grey
नई, नया, नए = new
पुरानी, पुराना, पुराने = old
कीमत, मूल्य, कीमती = value
कीमती सामान = valuables
सामान = belongings
कपड़े = clothes
दस्तावेज़ों = documents
# --- people
पुरुष, आदमी = man
महिला, औरत = woman
लड़का = boy
लड़की = girl
युवक = young man
युवती = young woman
व्यक्ति = person
लोग = people
बच्चा = child
बच्चे = children
बुजुर्ग = elderly person
पति = husband
पत्नी = wife
बेटा, पुत्र = son
बेटी, पुत्री = daughter
भाई = brother
बहन = sister
मां, माँ, माता = mother
पिताजी = father
ससुर = father-in-law
सास = mother-in-law
देवर = brother-in-law
जेठ = elder brother-in-law
ननद = sister-in-law
रिश्तेदार = relative
पड़ोसी = neighbour
दोस्त, मित्र = friend
साथी, साथियों = associate
साथियों के साथ = with associates
गिरोह, गैंग = gang
मालिक = owner
दुकानदार = shopkeeper
कर्मचारी = employee
ड्राइवर, चालक = driver
सिक्योरिटी गार्ड, गार्ड, चौकीदार = security guard
मैनेजर = manager
डॉक्टर = doctor
श्रीमती = Smt.
श्री = Shri
कुमारी = Kumari
सुश्री = Ms.
श्रीमान = Mr.
पुत्र श्री = son of Shri
उम्र, आयु = age
साल, वर्षीय = years old
# --- places
गांव, गाँव, ग्राम = village
शहर, नगर = city
मोहल्ला = locality
कॉलोनी = colony
गली = lane
सड़क, रोड, मार्ग = road
चौराहा, चौक = crossing
बाजार, बाज़ार, मार्केट = market
दुकान = shop
मकान = house
घर = house
फ्लैट = flat
कमरा = room
दफ्तर, कार्यालय, ऑफिस = office
स्कूल = school
कॉलेज = college
अस्पताल = hospital
मंदिर = temple
मस्जिद = mosque
रेलवे स्टेशन, रेल्वे स्टेशन = railway station
बस स्टैंड, बस अड्डा = bus stand
पार्किंग = parking
पेट्रोल पंप = petrol pump
होटल = hotel
सेक्टर = sector
ब्लॉक = block
वार्ड = ward
तहसील = tehsil
ग्रामीण = rural
सीमा = boundary
पास, नजदीक = near
पुल = bridge
मॉल = mall
कांप्लेक्स, कॉम्प्लेक्स = complex
एटीएम बूथ = ATM booth
# --- time
सुबह = morning
दोपहर = afternoon
शाम = evening
रात = night
रात्रि = night
आज = today
कल = yesterday
परसों = day before yesterday
बजे = o'clock | ADV
लगभग, करीब = approximately | ADV
के आसपास, के आस-पास = around | P:near
पूर्वाह्न = AM
अपराह्न = PM
दिन = day
सप्ताह = week
महीना, माह = month
घंटे = hours
मिनट = minutes
तभी = then | ADV
उसके बाद, इसके बाद = after that | ADV
तब = then | ADV
अचानक = suddenly | ADV
जनवरी = January
फरवरी = February
मार्च = March
अप्रैल = April
मई = May
जून = June
जुलाई = July
अगस्त = August
सितंबर, सितम्बर = September
अक्टूबर = October
नवंबर, नवम्बर = November
दिसंबर, दिसम्बर = December
# --- numbers
एक = one | NUM
दो = two | NUM
तीन = three | NUM
चार = four | NUM
पांच, पाँच = five | NUM
छह, छः = six | NUM
सात = seven | NUM
आठ = eight | NUM
नौ = nine | NUM
दस = ten | NUM
बीस = twenty | NUM
पचास = fifty | NUM
सौ = hundred | NUM
# --- verbs (full forms; inflection rules handle simple stems)
किया, किये, किए = did | V
करके, कर के = having done | ADV
की गई, की गयी, किया गया, किये गए, किए गए = was done | V
दर्ज किया, दर्ज की, दर्ज किए = registered | V
दर्ज कराई, दर्ज करायी, दर्ज कराया, दर्ज कराना = lodged | V
शिकायत दर्ज कराई = lodged a complaint | V
बताया, बताई, बताते, बताते हैं = stated | V
कहा, कहा गया = said | V
पूछा = asked | V
बोला, बोली = said | V
बुलाया = called | V
फोन किया, कॉल किया = called | V
मैसेज किया = messaged | V
भेजा, भेजे, भेजी, भेज दिया = sent | V
भेजने = sending | V
मांगा, मांगे, मांगी = demanded | V
मांग की = demanded | V
मांगने = demanding | V
दिया, दी, दिए, दिये = gave | V
लिया, ली, लिए, लिये = took | V
ले गया, ले गए, ले गई, ले गये, ले लिया = took away | V
लेकर = taking | ADV
लेकर फरार, लेकर भाग = absconded with | V
चुराकर, चुरा कर = having stolen | V
चुरा लिया, चुरा ली, चुरा ले गया, चुरा ले गए = stole | V
चुराया, चुराई, चुराए, चुरा = stole | V
चोरी हो गया, चोरी हो गई, चोरी हो गए, चोरी हुआ, चोरी हुई = was stolen | V
चोरी कर लिया, चोरी कर ली, चोरी कर ले गया, चोरी की, चोरी कर = stole | V
चोरी करके = having stolen | V
छीन लिया, छीना, छीनकर, छीन कर = snatched | V
लूट लिया, लूटा, लूटकर = robbed | V
मारा, मारे, मारी, मार दिया = hit | V
मारपीट की, मारपीट करने लगे, मारपीट करने लगा = assaulted | V
पीटा, पीटने = beat | V
धमकी दी, धमकाया, धमकाने = threatened | V
गाली दी, गालियां दी, गाली देने = abused | V
जान से मारने की धमकी = threat to kill
जान से मारने की धमकी दी = threatened to kill | V
भागा, भाग गया, भाग गए, भाग गई, भागकर, भाग कर, भाग निकले, भाग निकला = fled | V
फरार हो गया, फरार हो गए, फरार हो गई, फरार हुए = absconded | V
फरार = absconding
पकड़ा, पकड़ लिया, पकड़ लिए = caught | V
पकड़ा गया = was caught | V
गिरफ्तार किया, गिरफ्तार किए = arrested | V
देखा, देखी, देखे, देखते = saw | V
सुना = heard | V
आया, आई, आए, आये = came | V
गया, गई, गए, गये, गयी = went | V
जा रहा था, जा रही थी, जा रहे थे = was going | V
आ रहा था, आ रही थी, आ रहे थे = was coming | V
खड़ा, खड़ी, खड़े = standing | V
खड़ी की, खड़ी कर = parked | V
पार्क किया, पार्क की = parked | V
छोड़ा, छोड़ दिया = left | V
उठाया, उठा ले गया, उठा ले गए = picked up / took away | V
घुसकर, घुस कर, घुसे, घुस गए, घुस गया = entering | V
घुस आए = broke in | V
तोड़कर, तोड़ कर, तोड़ा, तोड़ दिया, तोड़ दी = broke | V
टूटा, टूटी, टूटा हुआ, टूटी हुई = broken | V
फोड़ दिया, फोड़ दी = smashed | V
बेचा, बेच दिया = sold | V
खरीदा = bought | V
जमा कराए, जमा कराए गए, जमा कराया, जमा कर दिए, जमा किए = deposited | V
ट्रांसफर किए, ट्रांसफर किया, ट्रांसफर कर दिए, ट्रांसफर करवाए = transferred | V
कटे, कट गए, कट गया, काट लिए = was debited | V
निकाल लिए, निकाल लिया, निकाले = withdrew | V
निकल गए, निकल गया = came out | V
ठगा, ठग लिया, ठग लिए = cheated | V
धोखा दिया, धोखा दे दिया = cheated | V
धोखाधड़ी की = committed fraud | V
बहलाया, बहला फुसलाकर = lured | V
फुसलाकर, फुसला कर = enticing | V
अपहरण कर लिया, अपहरण कर ले गए = kidnapped | V
लापता हो गया, लापता हो गई, गायब हो गया, गायब हो गई = went missing | V
गायब था, गायब थी, गायब मिला, गायब मिली = was missing | V
मिला, मिली, मिले = found | V
पाया, पाई, पाए = found | V
पहुंचा, पहुंचे, पहुँचा, पहुंची = reached | V
पहुंचकर, पहुँचकर = on reaching | V
लौटा, लौटी, लौटे, वापस आया, वापस आने पर, लौटने पर = returned | V
हुआ, हुई, हुए, हो गया, हो गई, हो गए, हो गयी = happened | V
होने = being | V
रहा, रही, रहे = was (continuing) | V
कर रहा था, कर रही थी, कर रहे थे = was doing | V
करने लगा, करने लगे, करने लगी = started to do | V
करना = to do | V
करता, करती, करते = does | V
करवाई, कार्रवाई, कार्यवाही = action
करने की मांग = demand to take
कार्रवाई की जाए, कार्यवाही की जाए, कार्यवाही करने = action be taken | V
विधिक कार्यवाही = legal action
उचित कार्यवाही = appropriate action
अनुरोध, निवेदन = request
अनुरोध है, निवेदन है = it is requested | V
जांच की जा रही है, जांच जारी है = investigation is under way | V
जांच शुरू की, जांच प्रारंभ, विवेचना प्रारंभ = investigation started | V
जांच = investigation
तफ्तीश, विवेचना = investigation
पता चला, पता लगा, पता लगाया = came to know | V
याद = remember | V
शक है, शक जताया, संदेह है = suspected | V
शक करते हैं, संदेह करते हैं = suspect | V
मौजूद, मौजूद थे, मौजूद था = present | V
थे, थीं = were | AUX
था, थी = was | AUX
है = is | AUX
हैं = are | AUX
हूं, हूँ = am | AUX
होगा, होगी, होंगे = will be | AUX
नहीं, न, ना = not | NEG
कभी नहीं = never | NEG
# --- pronouns / conjunctions / adverbs
मैं = I | PRON
मैंने = I | PRON
मेरा, मेरी, मेरे = my | PRON
मुझे, मुझको = me | PRON
हम = we | PRON
हमने = we | PRON
हमारा, हमारी, हमारे = our | PRON
आप = you | PRON
आपका, आपकी = your | PRON
तुम = you | PRON
वह, वो = he/she | PRON
उसने, उन्होंने = he/she | PRON
उसका, उसकी, उसके = his/her | PRON
उसे, उन्हें, उनको, उसको = him/her | PRON
उनका, उनकी, उनके = their | PRON
यह, ये = this | PRON
इस, इसे, इन = this | PRON
इसका, इसकी, इसके = its | PRON
उस, उन = that | PRON
जो = who | PRON
कौन = who | PRON
क्या = what | PRON
कहाँ, कहां = where | PRON
कब = when | PRON
कैसे = how | PRON
अपना, अपनी, अपने = own | PRON
खुद = himself | PRON
सभी, सब = all | PRON
कुछ = some | PRON
कोई = some | PRON
और = and | CONJ
एवं, तथा = and | CONJ
या = or | CONJ
लेकिन, परंतु, किंतु, मगर = but | CONJ
कि = that | CONJ
क्योंकि = because | CONJ
इसलिए = therefore | CONJ
जब = when | CONJ
जबकि = while | CONJ
अगर, यदि = if | CONJ
तो = then | CONJ
भी = also | ADV
ही = only | ADV
केवल, सिर्फ = only | ADV
फिर = then | ADV
वहां, वहाँ = there | ADV
यहां, यहाँ = here | ADV
अभी = now | ADV
पहले = earlier | ADV
बाद = later | ADV
लगातार = continuously | ADV
जबरन, जबरदस्ती, ज़बरदस्ती = forcibly | ADV
धोखे से = by deceit | ADV
अकेले = alone | ADV
साथ = along | ADV
बहुत = very | ADV
काफी = quite | ADV
कुल = total | ADV
अपने आप = by himself | ADV
ऐसा = such | ADV
इस प्रकार = thus | ADV
उपरोक्त, उपरोक्त वर्णित = the above-mentioned | ADV
दिनांकित = dated | ADV
सुमारे = approximately | ADV
# --- postpositions
ने = | P:agent
को = to | P:dat
से = from | P:abl
में = in | P:loc
पर = on | P:on
का, की, के = of | P:gen
तक = until | P:til
द्वारा = by | P:by
के द्वारा = by | P:by
के लिए, के लिये, हेतु = for | P:for
के साथ, साथ में = with | P:with
के पास = near | P:near
के बाद = after | P:after
के पहले, से पहले = before | P:before
के बिना, बिना = without | P:without
के अनुसार = according to | P:acc
के सामने = in front of | P:front
के अंदर, के अन्दर = inside | P:loc
के बाहर = outside | P:out
के ऊपर = above | P:on
के नीचे = below | P:under
के पीछे = behind | P:behind
के बारे में = about | P:about
के खिलाफ, के विरुद्ध = against | P:against
के नाम पर, के नाम से = in the name of | P:for
के दौरान = during | P:during
की ओर, की तरफ = towards | P:toward
से लेकर = from | P:abl
द्वारा किया गया = done by | P:by
"""

MR = """
प्रथम माहिती अहवाल = First Information Report | LBL
एफआयआर क्रमांक, एफआयआर क्र. = FIR No. | LBL
जिल्हा = District | LBL
पोलीस ठाणे, पोलिस ठाणे, पोलीस स्टेशन = Police Station | LBL
वर्ष = Year | LBL
दिनांक, तारीख = Date | LBL
वेळ = Time | LBL
घटनेचे ठिकाण, घटनास्थळ, गुन्ह्याचे ठिकाण, घटनास्थळी = Place of occurrence | LBL
घटनेचे वर्णन, घटनेचा तपशील, वर्णन, तपशील = Incident details | LBL
तक्रारदार, फिर्यादी, अर्जदार = Complainant | LBL
माहितीदार = Informant
वडिलांचे नाव, वडिलांचे = Father's name | LBL
पत्ता, राहण्याचा पत्ता = Address | LBL
आरोपी = Accused
संशयित, संशयीत = Suspect
अज्ञात = Unknown
अज्ञात व्यक्ती, अज्ञात इसम, अज्ञात इसमाने = unknown person
तपास अधिकारी, तपासी अधिकारी = Investigating Officer | LBL
पोलीस उपनिरीक्षक, सहायक पोलीस निरीक्षक = Police Sub-Inspector
पोलीस निरीक्षक = Police Inspector
पोलीस हवालदार, हवालदार = Police Constable
पोलीस, पोलिस = police
पोलिसांनी, पोलीसांनी = the police
कलम, कलमे = Section | LBL
भा.दं.वि., भादंवि = IPC
गुन्हा, गुन्ह्याचा = offence
गुन्हा दाखल, गुन्हा नोंद, गुन्हा नोंदवला, गुन्हा दाखल केला = case registered | V
प्रकरण नोंद = case registered
तक्रार, तक्रारी = complaint
तक्रार दाखल = complaint filed
साक्षीदार = witness
जखमी = injured
मृत = deceased
अटक = arrest
अटक केली = arrested | V
जामीन = bail
जबाब = statement
जप्त = seized
जप्त केले = seized | V
हस्तगत = recovered
ताबा = possession
चोरी = theft
चोरट्याने, चोरट्यांनी, चोरटा = thief
चोरीस गेले, चोरीस गेली, चोरीस गेला, चोरी झाली, चोरी झाले = was stolen | V
चोरून नेले, चोरून नेली, चोरून नेला, चोरुन नेले = stole and took away | V
चोरली, चोरले, चोरला = stole | V
चोरीचा माल, चोरीची मालमत्ता, चोरीस गेलेली मालमत्ता = stolen property | LBL
मालमत्ता = property
दरोडा = dacoity
जबरी चोरी = robbery
लूट = robbery
खून = murder
हत्या = murder
मारहाण = assault
हल्ला = attack
बलात्कार = rape
विनयभंग = outraging modesty
अपहरण = kidnapping
फसवणूक = fraud
फसवले, फसवून, फसवणूक केली = cheated | V
खंडणी = extortion
धमकी = threat
धमकी दिली, धमकावले = threatened | V
शिवीगाळ = abuse
शिवीगाळ केली = abused | V
हुंडा = dowry
छळ = harassment
घरफोडी = house-breaking
आग = fire
जाळपोळ = arson
तोडफोड = vandalism
जुगार = gambling
लाच = bribe
अंमली पदार्थ = narcotics
गांजा = ganja
शस्त्र, हत्यार = weapon
चाकू = knife
कोयता = sickle
पिस्तूल = pistol
गावठी कट्टा = country-made pistol
काठी = stick
सायबर फसवणूक, ऑनलाइन फसवणूक = online fraud
ऑनलाइन = online
बँक खाते, बँक खात्यातून = bank account
खाते, खात्यात = account
खाते क्रमांक = account number
पैसे, रक्कम = money
रोख, रोकड = cash
रुपये, रुपयांची, रुपयांचा = rupees
लाख = lakh
हजार = thousand
कोटी = crore
सोन्याची चेन, सोन्याचे गंठण = gold chain
सोने, सोन्याचे, सोन्याची = gold
चांदी = silver
दागिने = jewellery
मोबाईल, मोबाइल = mobile
मोबाईल फोन = mobile phone
मोबाईल क्रमांक = mobile number
क्रमांक = number
लॅपटॉप = laptop
बॅग = bag
पर्स = purse
घड्याळ = watch
चावी = key
कुलूप = lock
मोटारसायकल, मोटर सायकल = motorcycle
दुचाकी = two-wheeler
चारचाकी = four-wheeler
स्कूटर = scooter
वाहन, गाडी = vehicle
कार = car
ट्रक = truck
रिक्षा = rickshaw
काळा, काळी, काळ्या, काळे = black
पांढरा, पांढरी, पांढऱ्या = white
लाल = red
निळा, निळी, निळ्या = blue
हिरवा, हिरवी = green
पिवळा = yellow
राखाडी, करडा, करडी = grey
हेल्मेट = helmet
पार्किंग = parking
नुकसान = damage
काच = glass
मागील = rear
समोरील = front
पोलीस स्टेशनला = to the police station
तालुका = taluka
गाव = village
शहर = city
वस्ती = settlement
रस्ता, रस्त्यावर = road
चौक = crossing
बाजार = market
दुकान = shop
घर = house
इमारत = building
कार्यालय, ऑफिस = office
शाळा = school
रुग्णालय = hospital
मंदिर = temple
बस स्थानक = bus station
रेल्वे स्टेशन = railway station
महामार्ग = highway
सकाळी = in the morning
दुपारी = in the afternoon
सायंकाळी, संध्याकाळी = in the evening
रात्री = at night
आज = today
काल = yesterday
सुमारे = approximately
रोजी = on
वाजता, वाजेच्या = at | P:at
दरम्यान = during | P:during
पासून = from | P:abl
पर्यंत = until | P:til
मध्ये = in | P:loc
च्या, चा, ची, चे = of | P:gen
साठी = for | P:for
सोबत, बरोबर = with | P:with
कडे = to | P:dat
कडून = from | P:abl
वर = on | P:on
खाली = below | P:under
जवळ = near | P:near
आत = inside | P:loc
बाहेर = outside | P:out
विरुद्ध = against | P:against
नुसार = according to | P:acc
आणि, व = and | CONJ
किंवा = or | CONJ
परंतु, पण = but | CONJ
कारण = because | CONJ
म्हणून = therefore | CONJ
की = that | CONJ
तसेच = also | CONJ
आहे = is | AUX
आहेत = are | AUX
होते, होता, होती = was | AUX
नाही, नाहीत = not | NEG
केले, केला, केली = did | V
केल्याचे = having done | V
झाले, झाला, झाली, झाल्याचे = happened | V
आले, आला, आली = came | V
गेले, गेला, गेली = went | V
पळून गेला, पळून गेली, पळून गेले, पळून जाताना, पळून = fled | V
फरार = absconding
फरार झाला, फरार झाले = absconded | V
दिले, दिला, दिली = gave | V
घेतले, घेतला, घेतली = took | V
घेऊन गेला, घेऊन गेली, घेऊन गेले, घेऊन जाताना = took away | V
घेऊन = taking | V
सांगितले, सांगितला = told | V
बोलावले = called | V
फोन केला, कॉल केला = called | V
पाहिले, पाहिला, पाहिली, पाहिल्याचे = saw | V
ऐकले = heard | V
मारले, मारला, मारली = hit | V
मारहाण केली = assaulted | V
पकडले, पकडला = caught | V
उभी, उभा, उभे = standing | V
उभी केली, पार्क केले, पार्क केली = parked | V
आढळले, आढळून आले, आढळली = found | V
आढळून आले की = found that | V
परत आल्यानंतर, परत आल्यावर = after returning | V
गायब, गायब असल्याचे = missing
गहाळ झाले, गहाळ झाली, गहाळ = went missing | V
बेपत्ता = missing
पाठवले, पाठवली, पाठविले = sent | V
मागितले, मागितली = demanded | V
जमा केले, जमा केली = deposited | V
काढले, काढून घेतले = withdrew | V
वळते केले, वळवले = transferred | V
तोडले, तोडून = broke | V
फोडले, फुटलेली, फुटलेला, फुटले = broken | V
तपास सुरू केला, तपास सुरू आहे = investigation started | V
तपास = investigation
संशय = suspicion
संशय आहे = suspected | V
मी = I | PRON
मला = me | PRON
माझा, माझी, माझे, माझ्या = my | PRON
आम्ही = we | PRON
आमचा, आमची, आमचे, आमच्या = our | PRON
तो, ती, ते = he/she | PRON
त्याने, तिने, त्यांनी = he/she | PRON
त्याला, तिला, त्यांना = him/her | PRON
त्याचा, त्याची, त्याचे, त्याच्या, तिचा, तिची, तिचे, तिच्या = his/her | PRON
त्यांचा, त्यांची, त्यांचे, त्यांच्या = their | PRON
हा, ही, हे = this | PRON
या = this | PRON
त्या, तो = that | PRON
कोण = who | PRON
काय = what | PRON
सर्व = all | PRON
काही = some | PRON
यांनी = | P:agent
ने = | P:agent
ला = to | P:dat
ना = to | P:dat
काळ्या हेल्मेटमधील = wearing a black helmet | ADJ
काळ्या हेल्मेटमध्ये = wearing a black helmet | ADJ
"""

HX = """
# --- romanised Hindi.  Spelling variants are listed together.
ghatna, ghatana, vardaat, wardaat = incident
ghatna ka sthan, ghatna sthal, ghatnasthal, vardaat ka sthan = Place of occurrence | LBL
sthan, sthal, jagah = place
ladka, ladke, larka, larke = boy
ladki, ladkiyan = girl
bheed, bhid = crowd
jeb, pocket = pocket
urf = alias
rehne, rahne = living
bhagte, bhagta, bhagti, bhagna, bhaagte = running
thana, thane, police station = Police Station
zila, jila, jilla = District
dinank, dinaank, tarikh, tareekh, tithi = Date
samay, waqt, vakt = Time
varsh, saal = year
prathamik, pratham suchna report = First Information Report
shikayat, shikayat patra, tahrir = complaint
shikayatkarta, shikayatkartaa, shikayatakarta, pariwadi, parivadi, vadi, praarthi, prarthi = complainant
soochak, suchak = informant
aaropi, aropi, abhiyukt, mulzim = accused
sandigdh, sandehi, shak = suspect
agyat, agyaat, ajnat, agyat vyakti = unknown
adhikari, adhikaari = officer
jaanch adhikari, janch adhikari, vivechak = Investigating Officer
paitrik, pita ka naam = Father's name
pita, pitaji = father
mata, maa, mummy = mother
pati = husband
patni, biwi, bibi = wife
beta, putra = son
beti, putri = daughter
bhai = brother
behen, bahan, behan = sister
rishtedar, rishtedaar = relative
padosi, padosee = neighbour
dost, mitra = friend
saathi, sathi, saathiyon = associate
gang, giroh, giroh = gang
malik = owner
dukandar, dukaandaar = shopkeeper
karmachari = employee
driver, chalak = driver
guard, chowkidar = security guard
naam = name
pata = address
nivasi, nivasee, sakin = resident of
umar, umra, age = age
mobile, mobile number, mob no, mobile no = mobile
phone, telephone = phone
number, no = number
khata, account = account
khata number, khata sankhya = account number
bank = bank
rakam, rashi, dhanrashi = amount
paise, paisa, rupaye, rupay, rupaiye, rupees, rs = rupees
lakh, lac = lakh
karod, crore = crore
hazaar, hazar, hajar = thousand
nakad, nakdi, cash = cash
chori, chorii = theft
chor = thief
dakaiti, dakaity = dacoity
loot, lootpat = robbery
jhapatmari, chheena jhapti, chhinajhapti = snatching
hatya = murder
hatya ka prayas = attempt to murder
marpit, maarpeet, marpeet = assault
hamla, hamla = attack
balatkar = rape
chhedchhad, chhedkhani = molestation
apaharan = kidnapping
dhokhadhadi, dhokhadadi, dhokhadhari, thagi = fraud
thag = cheat
jaalsaazi, jalsazi = forgery
rangdari = extortion
dhamki, dhamkee = threat
blackmail = blackmail
dahej = dowry
gharelu hinsa = domestic violence
taskari = smuggling
nasha, nashila padarth = narcotics
ganja = ganja
sendhmari, nakabzani = house-breaking
aagjani = arson
todfod = vandalism
jua, juaa = gambling
rishwat, ghoos = bribe
hathiyar, hathyar = weapon
chaaku, chaku = knife
pistol, tamancha, katta = pistol
bandook, bandooq = gun
goli = bullet
danda, lathi = stick
cyber thagi, cyber fraud = cyber fraud
online = online
link = link
otp = OTP
atm = ATM
card = card
upi = UPI
lenden, len den, transaction = transaction
transfer = transfer
lottery = lottery
naukri = job
nivesh = investment
sim = SIM
call = call
message, msg = message
photo, tasveer = photo
video = video
whatsapp, whatsap = WhatsApp
telegram = Telegram
facebook = Facebook
instagram = Instagram
email = email
password = password
laptop = laptop
bag, baig = bag
purse = purse
wallet = wallet
sona, sone = gold
chandi = silver
gehne, gahne, jewar, jewellery = jewellery
chain = chain
anguthi = ring
ghadi = watch
chabi, chaabi = key
tala, taala = lock
motorcycle, motorsaikil = motorcycle
bike, baik = bike
scooter, scooty = scooter
car, gaadi, gadi = vehicle
truck = truck
auto = auto-rickshaw
cycle = bicycle
helmet = helmet
number plate = number plate
kala, kaala, kale, kali = black
safed, safaid, white = white
lal = red
neela, neeli, neele, nila = blue
hara, hari = green
peela, peeli = yellow
naya, nayi, naye = new
purana, purani, purane = old
keemat, kimat, mulya = value
saaman, samaan, saman = belongings
kapde = clothes
dastavez, dastawej, kagzaat, kagaz = documents
aadhaar, aadhar, adhar = Aadhaar
pan card = PAN card
license, licence = licence
cheque, check = cheque
karz, loan, rin = loan
zameen, jameen, zamin = land
plot = plot
gaon, gaanv, gram = village
shahar, nagar = city
mohalla, mohalle = locality
colony = colony
gali = lane
sadak, road, marg = road
chauraha, chowk = crossing
bazaar, bazar, market = market
dukan, dukaan = shop
makan = house
ghar = house
flat = flat
kamra, kamre = room
office, daftar, karyalay = office
school = school
college = college
hospital, aspatal = hospital
mandir = temple
masjid = mosque
railway station, station = railway station
bus stand, bus adda = bus stand
parking = parking
petrol pump = petrol pump
hotel = hotel
sector = sector
subah, subha, savere = morning
dopahar, dopehar = afternoon
shaam, sham = evening
raat, raatri, ratri = night
aaj = today
kal = yesterday
parso = day before yesterday
baje = o'clock | ADV
lagbhag, kareeb, kareeban = approximately | ADV
aaspaas = around | ADV
din = day
hafta, saptah = week
mahina, mahine, maah = month
ghante, ghanta = hours
minute = minutes
achanak, achaanak = suddenly | ADV
phir, fir = then | ADV
tab = then | ADV
uske baad, iske baad = after that | ADV
ek = one | NUM
do = two | NUM
teen = three | NUM
char, chaar = four | NUM
paanch, panch = five | NUM
chhe, chhah = six | NUM
saat = seven | NUM
aath = eight | NUM
nau = nine | NUM
das = ten | NUM
bees = twenty | NUM
pachas = fifty | NUM
sau = hundred | NUM
police = police
police adhikshak, sp = Superintendent of Police
sub inspector, si, daroga, darogha = Sub-Inspector
inspector, thanadhyaksh, thanedar = Inspector
asi = Assistant Sub-Inspector
head constable, hc = Head Constable
constable, sipahi, sipahee = Constable
kotwali = Kotwali (police station)
chowki = outpost
report, riport = report
case, mukadma, mukaddama, mamla, maamla = case
darj, darz = registered
gawah, gavah, sakshi, chashmdeed = witness
pidit, peedit = victim
ghayal, zakhmi = injured
mritak = deceased
apradh = crime
apradhi = criminal
jurm = offence
giraftar, giraftaar = arrested
hiraasat, hirasat = custody
jamanat, zamanat = bail
poochtachh, poochtaach, puchtachh = questioning
bayan = statement
talashi, talaashi = search
jabt, zabt = seized
baramad, baramadgi = recovery
kabza, kabja = possession
warrant = warrant
adalat, court = court
vakil, wakil = lawyer
saboot, sabut, sakshya = evidence
cctv, cctv footage = CCTV footage
footage = footage
jaanch, janch, tafteesh, vivechna = investigation
dhara, dhaara, dhaaraa = Section
adhiniyam = Act
avaidh, avaidh = illegal
fake, farzi, jaali, jali = fake
nakli, naqli = counterfeit
fraud = fraud
chori kiya, chori kar liya, chori kar li, chori kar liye, chori kar di, chori ho gaya, chori ho gayi, chori hua, chori hui = stole | V
chura liya, chura li, chura kar, churakar, chura ke, churaya, churaye, churai = stole | V
chura le gaya, chura le gaye, chura le gayi, chura ke le gaya, chura kar le gaya = stole and took away | V
chheen liya, chheen li, chheena, chheen kar, chheen ke, chhin liya = snatched | V
loot liya, loot li, loota, lootkar = robbed | V
maara, mara, maari, mara, maar diya, maar di = hit | V
maarpeet ki, marpit ki, maarpeet karne lage, maarpeet karne laga, maarpeet kiya = assaulted | V
peeta, peet diya, peetne = beat | V
dhamki di, dhamkaya, dhamkane = threatened | V
gaali di, gali di, gaaliyan di, gaali galoch = abused | V
jaan se maarne ki dhamki di, jaan se marne ki dhamki di = threatened to kill | V
jaan se maarne ki dhamki, jaan se marne ki dhamki = threat to kill
bhaga, bhag gaya, bhag gaye, bhag gayi, bhagkar, bhag kar, bhaag gaya, bhaag gaye, bhaag gayi, bhag nikle, bhag nikla = fled | V
farar, faraar = absconding
farar ho gaya, farar ho gaye, farar ho gayi, farar hue, faraar ho gaya = absconded | V
pakda, pakad liya, pakad liye = caught | V
pakda gaya = was caught | V
giraftar kiya, giraftar kar liya, giraftar kiye = arrested | V
dekha, dekhi, dekhe, dekhte, dekhkar = saw | V
suna, suni, sune = heard | V
aaya, aayi, aaye = came | V
gaya, gayi, gaye, gaya tha, gayi thi = went | V
ja raha tha, ja rahi thi, ja rahe the = was going | V
aa raha tha, aa rahi thi, aa rahe the = was coming | V
khada, khadi, khade = standing | V
khadi ki, khadi kar, khada kiya, park kiya, park ki = parked | V
chhoda, chhod diya, chhodkar = left | V
utha ke le gaya, utha kar le gaya, utha le gaya = took away | V
ghuskar, ghus kar, ghuse, ghus gaye, ghus gaya, ghus aaye = broke in | V
todkar, tod kar, toda, tod diya, tod di, tod dala = broke | V
toota, tooti, tootha, toota hua, tooti hui = broken | V
phod diya, phod di, phodkar = smashed | V
becha, bech diya, bech di = sold | V
khareeda, kharida = bought | V
jama kiye, jama karaye, jama karaya, jama kar diye, jama karwaye, jama karaye gaye = deposited | V
transfer kiye, transfer kiya, transfer kar diye, transfer karwaye, transfer karaye = transferred | V
kat gaye, kat gaya, kat gaye, kate, kate gaye = was debited | V
nikal liye, nikal liya, nikale, nikaal liye, nikaal liya = withdrew | V
thaga, thag liya, thag liye = cheated | V
dhokha diya, dhokha de diya = cheated | V
dhokhadhadi ki, dhokhadhadi kiya = committed fraud | V
behlaya, behla fuslakar, behla phuslakar = lured | V
fuslakar, phuslakar = enticing | V
apaharan kar liya, apaharan kar le gaye = kidnapped | V
laapata ho gaya, laapata ho gayi, gayab ho gaya, gayab ho gayi, laapata, lapata = went missing | V
gayab tha, gayab thi, gayab mila, gayab mili, gayab = missing
mila, mili, mile = found | V
paya, payi, paye = found | V
pahuncha, pahunche, pahunchi, pahunch kar, pahunchkar = reached | V
lauta, lauti, laute, wapas aaya, wapas aane par, lautne par, wapas aakar = returned | V
hua, hui, hue, ho gaya, ho gayi, ho gaye = happened | V
raha, rahi, rahe = was (continuing) | V
kar raha tha, kar rahi thi, kar rahe the = was doing | V
karne laga, karne lage, karne lagi = started doing | V
karna, karne = to do | V
karta, karti, karte = does | V
kiya, kiye, kia, kar diya, kar di, kar dia, kar diye = did | V
karke, kar ke, kar = having done | ADV
di gayi, kiya gaya, ki gayi, kiye gaye = was done | V
darj kiya, darj ki, darj kiye = registered | V
darj karaya, darj karayi, darj karwayi, darj karwaya, darj karana, darj karwana = lodged | V
bataya, batayi, bataye, batate, bata = stated | V
kaha, kahaa, kahe = said | V
poocha, puchha = asked | V
bola, boli, bole = said | V
bulaya, bulayi, bulaye = called | V
phone kiya, call kiya, phone kiye, call kiye = called | V
message kiya, msg kiya = messaged | V
bheja, bheje, bheji, bhej diya, bhej diye = sent | V
maanga, maange, maangi, maanga tha, maang ki, maangne = demanded | V
diya, diye, di, di thi = gave | V
liya, liye, li = took | V
le gaya, le gaye, le gayi, le liya = took away | V
lekar = taking | ADV
lekar farar, lekar bhag, lekar bhaag = absconded with | V
pata chala, pata laga, pata lagaya = came to know | V
shak hai, shak jataya, sandeh hai = suspected | V
shak karte hain, sandeh karte hain = suspect | V
maujood, maujud, maujood the, maujood tha = present | V
karwai, karrwai, karyavahi, karyawahi = action
karwai ki jaye, karyavahi ki jaye, karyawahi ki jaye, karwai karne = action be taken | V
kanooni karwai, vidhik karyavahi = legal action
uchit karyavahi, uchit karwai = appropriate action
nivedan, anurodh, request = request
nivedan hai, anurodh hai = it is requested | V
jaanch ki ja rahi hai, janch jari hai, jaanch jaari hai = investigation is under way | V
hai, hain, hai = is | AUX
hoon, hu, hun = am | AUX
tha, thi = was | AUX
the = were | AUX
hoga, hogi, honge = will be | AUX
nahi, nahin, nhi, na, mat = not | NEG
kabhi nahi = never | NEG
main, mai = I | PRON
maine = I | PRON
mera, meri, mere = my | PRON
mujhe, mujhko = me | PRON
hum = we | PRON
humne = we | PRON
hamara, hamari, hamare = our | PRON
aap = you | PRON
aapka, aapki, aapke = your | PRON
tum = you | PRON
tumne = you | PRON
wo, woh, vo, wah, vah = he/she | PRON
usne, unhone, unhonne = he/she | PRON
uska, uski, uske = his/her | PRON
usko, use, unko, unhe = him/her | PRON
unka, unki, unke = their | PRON
ye, yeh, yah = this | PRON
is, isko, ise, in = this | PRON
iska, iski, iske = its | PRON
us, un = that | PRON
jo = who | PRON
kaun = who | PRON
kya = what | PRON
kahan, kahaan = where | PRON
kab = when | PRON
kaise = how | PRON
apna, apni, apne = own | PRON
khud = himself | PRON
sab, sabhi = all | PRON
kuch = some | PRON
koi = some | PRON
aur = and | CONJ
evam, tatha = and | CONJ
ya = or | CONJ
lekin, parantu, kintu, magar = but | CONJ
ki = that | CONJ
kyunki, kyonki = because | CONJ
isliye, is liye = therefore | CONJ
jab = when | CONJ
jabki = while | CONJ
agar, yadi = if | CONJ
to = then | CONJ
bhi = also | ADV
hi = only | ADV
sirf, keval = only | ADV
wahan, waha, vahan = there | ADV
yahan, yaha = here | ADV
abhi = now | ADV
pehle, pahle = earlier | ADV
baad = later | ADV
lagatar = continuously | ADV
jabran, zabardasti, jabardasti = forcibly | ADV
dhokhe se = by deceit | ADV
akele = alone | ADV
saath = along | ADV
bahut = very | ADV
kaafi, kafi = quite | ADV
kul = total | ADV
upar, uprokt = above | ADV
dinankit = dated | ADV
ne = | P:agent
ko = to | P:dat
se = from | P:abl
mein, me = in | P:loc
par, pe = on | P:on
ka, ki, ke = of | P:gen
tak = until | P:til
dwara, dvara, dwaara = by | P:by
ke dwara = by | P:by
ke liye, ke lie, hetu = for | P:for
ke saath, ke sath, saath mein = with | P:with
ke paas, paas = near | P:near
ke baad = after | P:after
ke pehle, se pehle, ke pahle = before | P:before
ke bina, bina = without | P:without
ke anusar = according to | P:acc
ke samne, ke saamne = in front of | P:front
ke andar = inside | P:loc
ke bahar = outside | P:out
ke upar = above | P:on
ke neeche, ke niche = below | P:under
ke peeche, ke pichhe = behind | P:behind
ke baare mein, ke bare mein = about | P:about
ke khilaf, ke khilaaf, ke viruddh = against | P:against
ke naam par, ke naam se = in the name of | P:for
ke dauran = during | P:during
ki taraf, ki or, ki aur = towards | P:toward
wala, wali, wale, vala, vali, vale = the one (who) | ADJ
"""
