"""Core police / legal vocabulary for Bengali, Gujarati, Punjabi (Gurmukhi), Tamil, Telugu, Kannada, Malayalam and Urdu.

Same line format as lexicon_hi.py.  These languages get a word-for-word gloss (source word order is kept, no reordering) and
are never labelled better than "rule-based"; words that are not listed are marked as unknown.
"""

BN = """
প্রথম তথ্য প্রতিবেদন, প্রাথমিক তথ্য প্রতিবেদন = First Information Report | LBL
এফআইআর = FIR
জেলা = District | LBL
থানা = Police Station | LBL
নং, নম্বর, নাম্বার = No.
তারিখ = Date | LBL
সময় = Time | LBL
ধারা = Section | LBL
অভিযোগকারী, অভিযোগকারীর, অভিযোগকারিণী = Complainant | LBL
অভিযোগ = complaint
অভিযুক্ত, আসামি = accused
সন্দেহভাজন = suspect
পিতার নাম = Father's name | LBL
ঠিকানা = Address | LBL
মোবাইল = Mobile
ফোন = phone
মোবাইল ফোন = mobile phone
ঘটনার বিবরণ, বিবরণ = Incident details | LBL
ঘটনাস্থল = place of occurrence | LBL
এলাকা = area
গত = last
তারিখে = on the date
থেকে = from | P:abl
চুরি = theft
চুরি হয়েছে, চুরি হয় = was stolen | V
ডাকাতি = dacoity
ছিনতাই = snatching
প্রতারণা = fraud
জালিয়াতি = forgery
হত্যা, খুন = murder
মারধর = assault
হুমকি = threat
অপহরণ = kidnapping
ধর্ষণ = rape
টাকা = rupees
মূল্য, দাম = value
স্কুটার = scooter
গাড়ি, গাড়ী = vehicle
মোটরসাইকেল = motorcycle
নম্বরের = of number
পালিয়ে যায়, পালিয়ে গেছে, পালিয়ে যায় = fled | V
পালিয়ে = fleeing | V
তদন্তকারী কর্মকর্তা = Investigating Officer | LBL
তদন্ত = investigation
পুলিশ = police
সাক্ষী = witness
আহত = injured
গ্রেফতার, গ্রেপ্তার = arrested
ব্যাংক, ব্যাঙ্ক = bank
অ্যাকাউন্ট, হিসাব = account
মামলা = case
দায়ের = filed
এসআই = SI
এএসআই = ASI
পিতা = father
স্বামী = husband
স্ত্রী = wife
ছেলে = son
মেয়ে = daughter
ভাই = brother
বোন = sister
অজ্ঞাত = unknown
ব্যক্তি = person
এক = one | NUM
দুই = two | NUM
তিন = three | NUM
লাখ, লক্ষ = lakh
হাজার = thousand
কোটি = crore
নগদ = cash
সোনা = gold
গয়না = jewellery
ব্যাগ = bag
ল্যাপটপ = laptop
চাবি = key
ঘর, বাড়ি = house
দোকান = shop
বাজার = market
রাস্তা = road
রাত = night
সকাল = morning
বিকেল = afternoon
সন্ধ্যা = evening
আজ = today
গতকাল = yesterday
এবং, ও = and | CONJ
কিন্তু = but | CONJ
এর, র, ের = of | P:gen
তে, য়, ে = in | P:loc
কে = to | P:dat
দিয়ে = with | P:with
জন্য = for | P:for
হয়েছে = happened | V
হয় = happens | V
করেছে, করেন, করে = did | V
ছিল = was | AUX
আছে = is | AUX
না = not | NEG
"""

GU = """
પ્રથમ માહિતી અહેવાલ = First Information Report | LBL
એફઆઈઆર, એફ.આઈ.આર. = FIR
જિલ્લો = District | LBL
પોલીસ સ્ટેશન, પોલીસ મથક = Police Station | LBL
નંબર, ક્રમાંક = No.
તારીખ = Date | LBL
સમય = Time | LBL
કલમ = Section | LBL
ફરિયાદી = Complainant | LBL
ફરિયાદ = complaint
આરોપી = accused
શંકાસ્પદ = suspect
મોબાઇલ, મોબાઈલ = Mobile
વિગત = Incident details | LBL
છેતરપિંડી = fraud
ચોરી = theft
લૂંટ = robbery
હત્યા = murder
હુમલો = attack
ધમકી = threat
અપહરણ = kidnapping
રૂપિયા, રૂપિયાની = rupees
ખાતું, ખાતા = account
કાર = car
બાઇક = bike
મોટરસાયકલ = motorcycle
સ્કૂટર = scooter
ભાગી ગયો, ભાગી ગઈ, ભાગી ગયા = fled | V
ભાગી = fleeing | V
તપાસ = investigation
પોલીસ = police
સબ ઇન્સ્પેક્ટર = Sub-Inspector
સાક્ષી = witness
ઈજા = injury
ધરપકડ = arrest
નામ = name
પિતા = father
સરનામું = Address | LBL
પૈસા = money
સોનું = gold
બેગ = bag
દુકાન = shop
ઘર = house
રસ્તો = road
રાત = night
સવાર = morning
સાંજ = evening
આજે = today
ગઈકાલે = yesterday
એક = one | NUM
બે = two | NUM
ત્રણ = three | NUM
લાખ = lakh
હજાર = thousand
કરોડ = crore
અને = and | CONJ
સાથે = with | P:with
થઈ, થયું, થયો = happened | V
નંબરની, નંબરના = of number
મૂલ્ય, કિંમત = value
હતું, હતો, હતી = was | AUX
છે = is | AUX
ના, નહિ = not | NEG
"""

PA = """
ਪਹਿਲੀ ਸੂਚਨਾ ਰਿਪੋਰਟ = First Information Report | LBL
ਐਫ਼ਆਈਆਰ, ਐਫਆਈਆਰ = FIR
ਜ਼ਿਲ੍ਹਾ, ਜ਼ਿਲਾ = District | LBL
ਥਾਣਾ = Police Station | LBL
ਨੰਬਰ = No.
ਮਿਤੀ, ਤਾਰੀਖ਼ = Date | LBL
ਸਮਾਂ = Time | LBL
ਧਾਰਾ = Section | LBL
ਸ਼ਿਕਾਇਤਕਰਤਾ = Complainant | LBL
ਸ਼ਿਕਾਇਤ = complaint
ਦੋਸ਼ੀ, ਮੁਲਜ਼ਮ = accused
ਸ਼ੱਕੀ = suspect
ਮੋਬਾਈਲ = Mobile
ਵੇਰਵਾ = Incident details | LBL
ਧੋਖਾਧੜੀ = fraud
ਚੋਰੀ = theft
ਲੁੱਟ = robbery
ਕਤਲ = murder
ਹਮਲਾ = attack
ਧਮਕੀ = threat
ਅਗਵਾ = kidnapping
ਰੁਪਏ = rupees
ਖਾਤਾ = account
ਕਾਰ = car
ਮੋਟਰਸਾਈਕਲ = motorcycle
ਸਕੂਟਰ = scooter
ਫ਼ਰਾਰ = absconding
ਭੱਜ ਗਿਆ, ਭੱਜ ਗਏ = fled | V
ਜਾਂਚ = investigation
ਪੁਲਿਸ, ਪੁਲਸ = police
ਸਬ ਇੰਸਪੈਕਟਰ = Sub-Inspector
ਗਵਾਹ = witness
ਜ਼ਖ਼ਮੀ = injured
ਗ੍ਰਿਫ਼ਤਾਰ = arrested
ਨਾਂ, ਨਾਮ = name
ਪਿਤਾ = father
ਪਤਾ = Address | LBL
ਪੈਸੇ = money
ਸੋਨਾ = gold
ਬੈਗ = bag
ਦੁਕਾਨ = shop
ਘਰ = house
ਸੜਕ = road
ਰਾਤ = night
ਸਵੇਰ = morning
ਸ਼ਾਮ = evening
ਅੱਜ = today
ਕੱਲ੍ਹ = yesterday
ਇੱਕ = one | NUM
ਦੋ = two | NUM
ਤਿੰਨ = three | NUM
ਲੱਖ = lakh
ਹਜ਼ਾਰ = thousand
ਕਰੋੜ = crore
ਅਤੇ, ਤੇ = and | CONJ
ਨੇ = | P:agent
ਨੂੰ = to | P:dat
ਤੋਂ = from | P:abl
ਵਿੱਚ, ਵਿਚ = in | P:loc
ਦਾ, ਦੀ, ਦੇ = of | P:gen
ਸੀ = was | AUX
ਹੈ = is | AUX
ਹਨ = are | AUX
ਨਹੀਂ = not | NEG
ਕੀਤੀ, ਕੀਤਾ, ਕੀਤੇ = did | V
"""

TA = """
முதல் தகவல் அறிக்கை = First Information Report | LBL
எஃப்.ஐ.ஆர், எஃப்ஐஆர் = FIR
மாவட்டம் = District | LBL
காவல் நிலையம் = Police Station | LBL
எண் = No.
தேதி = Date | LBL
நேரம் = Time | LBL
பிரிவு = Section | LBL
புகார்தாரர் = Complainant | LBL
புகார்தாரரிடம் = from the complainant
புகார் = complaint
குற்றவாளி = accused
சந்தேக நபர் = suspect
கைபேசி = Mobile
தொலைபேசி = phone
மொபைல் = mobile
விவரம் = Incident details | LBL
மோசடி = fraud
திருட்டு = theft
கொள்ளை = robbery
கொலை = murder
தாக்குதல் = attack
மிரட்டல் = threat
கடத்தல் = kidnapping
ரூபாய் = rupees
கணக்கு = account
கணக்கு எண் = account number
கார் = car
மோட்டார் சைக்கிள் = motorcycle
இருசக்கர வாகனம் = two-wheeler
ஸ்கூட்டர் = scooter
வாகனம் = vehicle
தப்பினார், தப்பிச் சென்றார், தப்பி ஓடினார் = escaped | V
செய்யப்பட்டது = was done | V
திருடப்பட்டது = was stolen | V
விசாரணை = investigation
உதவி ஆய்வாளர் = Sub-Inspector
ஆய்வாளர் = Inspector
காவலர் = constable
காவல் = police
சாட்சி = witness
காயம் = injury
கைது = arrest
பெயர் = name
தந்தை = father
முகவரி = Address | LBL
பணம் = money
நகை = jewellery
தங்கம் = gold
பை = bag
கடை = shop
வீடு = house
சாலை = road
இரவு = night
காலை = morning
மாலை = evening
இன்று = today
நேற்று = yesterday
ஒரு = one | NUM
இரண்டு = two | NUM
மூன்று = three | NUM
லட்சம் = lakh
ஆயிரம் = thousand
கோடி = crore
மற்றும் = and | CONJ
என்ற = named
சம்பவம் = incident
"""

TE = """
ప్రథమ సమాచార నివేదిక = First Information Report | LBL
ఎఫ్ఐఆర్ = FIR
జిల్లా = District | LBL
పోలీస్ స్టేషన్, పోలీసు స్టేషన్ = Police Station | LBL
నంబర్, సంఖ్య = No.
తేదీ = Date | LBL
సమయం = Time | LBL
సెక్షన్, సెక్షన్లు = Section | LBL
ఫిర్యాదుదారు, ఫిర్యాదుదారుడు = Complainant | LBL
ఫిర్యాదు = complaint
నిందితుడు, నిందితురాలు = accused
అనుమానితుడు = suspect
మొబైల్ = Mobile
ఫోన్ = phone
వివరాలు = Incident details | LBL
మోసం = fraud
దొంగతనం, చోరీ = theft
దోపిడీ = robbery
హత్య = murder
దాడి = attack
బెదిరింపు = threat
కిడ్నాప్ = kidnapping
రూపాయలు = rupees
ఖాతా = account
కారు = car
బైక్ = bike
మోటార్ సైకిల్ = motorcycle
స్కూటర్ = scooter
పారిపోయాడు, పారిపోయారు = fled | V
దర్యాప్తు = investigation
సబ్ ఇన్‌స్పెక్టర్ = Sub-Inspector
ఇన్‌స్పెక్టర్ = Inspector
పోలీసు, పోలీస్ = police
సాక్షి = witness
గాయపడ్డారు = injured
అరెస్టు = arrest
పేరు = name
తండ్రి = father
చిరునామా = Address | LBL
డబ్బు = money
బంగారం = gold
నగలు = jewellery
బ్యాగ్ = bag
దుకాణం = shop
ఇల్లు = house
రోడ్డు = road
రాత్రి = night
ఉదయం = morning
సాయంత్రం = evening
ఈరోజు = today
నిన్న = yesterday
ఒక = one | NUM
రెండు = two | NUM
మూడు = three | NUM
లక్ష, లక్షలు = lakh
వేల, వేలు = thousand
కోటి = crore
మరియు = and | CONJ
"""

KN = """
ಪ್ರಥಮ ಮಾಹಿತಿ ವರದಿ = First Information Report | LBL
ಜಿಲ್ಲೆ = District | LBL
ಪೊಲೀಸ್ ಠಾಣೆ = Police Station | LBL
ದಿನಾಂಕ = Date | LBL
ಸಮಯ = Time | LBL
ಕಲಂ, ಸೆಕ್ಷನ್ = Section | LBL
ದೂರುದಾರ, ದೂರುದಾರರು = Complainant | LBL
ದೂರು = complaint
ಆರೋಪಿ = accused
ಶಂಕಿತ = suspect
ಮೊಬೈಲ್ = Mobile
ವಿವರ = Incident details | LBL
ವಂಚನೆ = fraud
ಕಳ್ಳತನ = theft
ದರೋಡೆ = robbery
ಕೊಲೆ = murder
ಹಲ್ಲೆ = attack
ಬೆದರಿಕೆ = threat
ಅಪಹರಣ = kidnapping
ರೂಪಾಯಿ = rupees
ಖಾತೆ = account
ಕಾರು = car
ಬೈಕ್ = bike
ಸ್ಕೂಟರ್ = scooter
ತನಿಖೆ = investigation
ಸಬ್ ಇನ್ಸ್‌ಪೆಕ್ಟರ್ = Sub-Inspector
ಪೊಲೀಸ್ = police
ಸಾಕ್ಷಿ = witness
ಗಾಯ = injury
ಬಂಧನ = arrest
ಹೆಸರು = name
ತಂದೆ = father
ವಿಳಾಸ = Address | LBL
ಹಣ = money
ಚಿನ್ನ = gold
ಬ್ಯಾಗ್ = bag
ಅಂಗಡಿ = shop
ಮನೆ = house
ರಸ್ತೆ = road
ರಾತ್ರಿ = night
ಬೆಳಿಗ್ಗೆ = morning
ಸಂಜೆ = evening
ಇಂದು = today
ನಿನ್ನೆ = yesterday
ಒಂದು = one | NUM
ಎರಡು = two | NUM
ಮೂರು = three | NUM
ಲಕ್ಷ = lakh
ಸಾವಿರ = thousand
ಕೋಟಿ = crore
ಮತ್ತು = and | CONJ
"""

ML = """
പ്രഥമ വിവര റിപ്പോർട്ട് = First Information Report | LBL
ജില്ല = District | LBL
പോലീസ് സ്റ്റേഷൻ = Police Station | LBL
തീയതി = Date | LBL
സമയം = Time | LBL
വകുപ്പ് = Section | LBL
പരാതിക്കാരൻ, പരാതിക്കാരി = Complainant | LBL
പരാതി = complaint
പ്രതി = accused
സംശയിക്കുന്ന = suspect
മൊബൈൽ = Mobile
വിവരങ്ങൾ = Incident details | LBL
തട്ടിപ്പ് = fraud
മോഷണം = theft
കവർച്ച = robbery
കൊലപാതകം = murder
ആക്രമണം = attack
ഭീഷണി = threat
രൂപ = rupees
അക്കൗണ്ട് = account
കാർ = car
ബൈക്ക് = bike
സ്കൂട്ടർ = scooter
അന്വേഷണം = investigation
സബ് ഇൻസ്പെക്ടർ = Sub-Inspector
പോലീസ് = police
സാക്ഷി = witness
പരിക്ക് = injury
അറസ്റ്റ് = arrest
പേര് = name
പിതാവ് = father
വിലാസം = Address | LBL
പണം = money
സ്വർണം = gold
ബാഗ് = bag
കട = shop
വീട് = house
റോഡ് = road
രാത്രി = night
രാവിലെ = morning
വൈകുന്നേരം = evening
ഇന്ന് = today
ഇന്നലെ = yesterday
ഒരു = one | NUM
രണ്ട് = two | NUM
മൂന്ന് = three | NUM
ലക്ഷം = lakh
ആയിരം = thousand
കോടി = crore
"""

UR = """
ابتدائی اطلاعی رپورٹ = First Information Report | LBL
ایف آئی آر = FIR
ضلع = District | LBL
تھانہ = Police Station | LBL
نمبر = No.
تاریخ = Date | LBL
وقت = Time | LBL
دفعہ = Section | LBL
شکایت کنندہ = Complainant | LBL
شکایت = complaint
ملزم = accused
مشتبہ = suspect
موبائل = Mobile
تفصیل = Incident details | LBL
دھوکہ دہی, دھوکا دہی = fraud
چوری = theft
ڈکیتی = dacoity
لوٹ = robbery
قتل = murder
حملہ = attack
دھمکی = threat
اغوا = kidnapping
روپے = rupees
کھاتہ, اکاؤنٹ = account
کار = car
موٹر سائیکل = motorcycle
اسکوٹر = scooter
فرار = absconding
تفتیش = investigation
سب انسپکٹر = Sub-Inspector
پولیس = police
گواہ = witness
زخمی = injured
گرفتار = arrested
نام = name
والد = father
پتہ = Address | LBL
پیسے = money
سونا = gold
بیگ = bag
دکان = shop
گھر = house
سڑک = road
رات = night
صبح = morning
شام = evening
آج = today
کل = yesterday
ایک = one | NUM
دو = two | NUM
تین = three | NUM
لاکھ = lakh
ہزار = thousand
کروڑ = crore
اور = and | CONJ
مورخہ = dated
قیمت = value
ہو گئی, ہوگئی = happened | V
کو = to | P:dat
سے = from | P:abl
میں = in | P:loc
کی, کا, کے = of | P:gen
تھی, تھا = was | AUX
ہے, ہیں = is | AUX
"""

OTHER = {"bn": BN, "gu": GU, "pa": PA, "ta": TA, "te": TE, "kn": KN, "ml": ML, "ur": UR}
